name: Run checks

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  push:
    branches:
      - main

jobs:
  show_diff:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get changes
        id: getchange
        run: |
          echo "::set-output name=changes::$(git diff --name-only origin/main..origin/${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}})"

      - name: Add comments
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            var changes = '${{ steps.getchange.outputs.changes }}'
            var files = changes.split('\n')
            for (var i = 0; i < files.length; i++) {
              var comment = `The file ${files[i]} is modified.`
              var issue_number = ${{ github.event.pull_request.number }}
              github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue_number,
                body: comment
              })
            }

  jest:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./front-end

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Run Jest Tests
        run: npm run test

  cypress:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./front-end

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install
        env:
          PORT: 3000

      - name: Run Local Server and Run Cypress Tests
        run: |
          npm run build
          npm run start &
          npx cypress run
        env:
          API_URI: http://localhost:3000/

  prettier:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./front-end

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Check Code Formatting with Prettier
        run: npx prettier {src,cypress} -c
